name: hf
channels:
  - https://conda.software.inl.gov/public
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - brotlipy=0.7.0=py39hb9d737c_1004
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.9.24=ha878542_0
  - certifi=2022.9.24=pyhd8ed1ab_0
  - cffi=1.15.1=py39he91dace_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - colorama=0.4.5=pyhd8ed1ab_0
  - conda=22.9.0=py39hf3d152e_1
  - conda-package-handling=1.9.0=py39hb9d737c_0
  - cryptography=38.0.1=py39hd97740a_0
  - icu=70.1=h27087fc_0
  - idna=3.4=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.19.3=h3790be6_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libarchive=3.5.2=hb890918_3
  - libcurl=7.85.0=h7bff187_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgomp=12.1.0=h8d9b700_16
  - libiconv=1.17=h166bdaf_0
  - libmamba=0.27.0=h0dd8ff0_0
  - libmambapy=0.27.0=py39hd55135b_0
  - libnghttp2=1.47.0=hdcd2b5c_1
  - libnsl=2.0.0=h7f98852_0
  - libsolv=0.7.22=h6239696_0
  - libsqlite=3.39.4=h753d276_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libuuid=2.32.1=h7f98852_1000
  - libxml2=2.10.2=h4c7fe37_1
  - libzlib=1.2.12=h166bdaf_4
  - lz4-c=1.9.3=h9c3ff4c_1
  - lzo=2.10=h516909a_1000
  - mamba=0.27.0=py39hfa8f2c8_0
  - ncurses=6.3=h27087fc_1
  - openssl=1.1.1q=h166bdaf_0
  - pip=22.2.2=pyhd8ed1ab_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.3=py39hb9d737c_1010
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.13=h9a8a25e_0_cpython
  - python_abi=3.9=2_cp39
  - readline=8.1.2=h0f457ee_0
  - reproc=14.2.3=h7f98852_0
  - reproc-cpp=14.2.3=h9c3ff4c_0
  - requests=2.28.1=pyhd8ed1ab_1
  - ruamel_yaml=0.15.80=py39hb9d737c_1007
  - setuptools=65.4.1=pyhd8ed1ab_0
  - sqlite=3.39.4=h4ff8645_0
  - tk=8.6.12=h27826a3_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tqdm=4.64.1=pyhd8ed1ab_0
  - urllib3=1.26.11=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yaml-cpp=0.7.0=h27087fc_2
  - zstd=1.5.2=h6239696_4
  - pip:
    - altair==4.2.0
    - asttokens==2.0.8
    - attrs==22.1.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - blinker==1.5
    - bokeh==2.4.1
    - boto3==1.24.86
    - botocore==1.27.86
    - bs4==0.0.1
    - cachetools==5.2.0
    - click==8.1.3
    - commonmark==0.9.1
    - debugpy==1.6.3
    - decorator==5.1.1
    - entrypoints==0.4
    - executing==1.1.0
    - gensim==4.2.0
    - gitdb==4.0.9
    - gitpython==3.1.27
    - importlib-metadata==5.0.0
    - ipykernel==6.16.0
    - ipython==8.5.0
    - ipywidgets==8.0.2
    - jedi==0.18.1
    - jinja2==3.1.2
    - jmespath==1.0.1
    - joblib==1.2.0
    - jsonschema==4.16.0
    - jupyter-client==7.3.5
    - jupyter-core==4.11.1
    - jupyterlab-widgets==3.0.3
    - markupsafe==2.1.1
    - matplotlib-inline==0.1.6
    - nest-asyncio==1.5.6
    - numpy==1.23.3
    - packaging==21.3
    - pandas==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.2.0
    - prompt-toolkit==3.0.31
    - protobuf==3.20.3
    - psutil==5.9.2
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==9.0.0
    - pydeck==0.8.0b3
    - pygments==2.13.0
    - pympler==1.0.1
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pytz==2022.4
    - pytz-deprecation-shim==0.1.0.post0
    - pyyaml==6.0
    - pyzmq==24.0.1
    - rich==12.6.0
    - s3transfer==0.6.0
    - scikit-learn==1.1.2
    - scipy==1.9.1
    - semver==2.13.0
    - six==1.16.0
    - sklearn==0.0
    - smart-open==6.2.0
    - smmap==5.0.0
    - soupsieve==2.3.2.post1
    - stack-data==0.5.1
    - streamlit==1.13.0
    - threadpoolctl==3.1.0
    - toml==0.10.2
    - tornado==6.2
    - traitlets==5.4.0
    - typing-extensions==4.3.0
    - tzdata==2022.4
    - tzlocal==4.2
    - validators==0.20.0
    - watchdog==2.1.9
    - wcwidth==0.2.5
    - widgetsnbextension==4.0.3
    - zipp==3.8.1
